#!/usr/bin/env bash

WM=${WM:=awesome}

xset r rate 180 35
setxkbmap -option caps:escape

XDG_DATA_HOME="$HOME/.local/share"
XDG_CONFIG_HOME="$HOME/.config"

PATH=$HOME/.local/bin:/sbin:$PATH

exec $WM >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
