#!/usr/bin/env bash

/usr/bin/xset r rate 180 35

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$HOME/.steambin/:$PATH"
fi

XDG_DATA_HOME="$HOME/.local/share"
XDG_CONFIG_HOME="$HOME/.config"
